sudo: required

language: java

services:
  - docker

jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_script:
  - docker images

before_deploy:
  - docker login docker.io -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker build -f Dockerfile -t malberra/ci-example:latest .
  - docker tag malberra/ci-example:latest malberra/ci-example

deploy:
  provider: script
  script: docker push malberra/ci-example
  on:
    branch: master